apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  annotations:
    helm.sh/order-weight: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cilium.io/v2","kind":"CiliumClusterwideNetworkPolicy","metadata":{"annotations":{"helm.sh/order-weight":"2"},"name":"allow-host-dns-and-sniff"},"spec":{"egress":[{"toEntities":["host","cluster"],"toPorts":[{"ports":[{"port":"53","protocol":"ANY"}],"rules":{"dns":[{"matchPattern":"*"}]}}]}],"endpointSelector":{}}}
  creationTimestamp: "2022-08-30T13:43:22Z"
  generation: 1
  name: allow-host-dns-and-sniff
  resourceVersion: "1598452243"
  uid: f70161a2-862b-4300-8b1d-b488b4525412
spec:
  egress:
  - toEntities:
    - host
    - cluster
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector: {}
--
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: core-community-slack-bot-egress-policy
spec:
  description: Allow egress to googleapis and slack
  egress:
  - toFQDNs:
    - matchPattern: '*.googleapis.com'
    - matchPattern: '*.slack.com'
    - matchPattern: slack.com
    - matchPattern: '*'
  endpointSelector: {}